import SocialIcon from './SocialIcon.jsx';
import React,{useEffect,useId,useRef,useState} from 'react';
import {Link,NavLink,useLocation} from 'react-router-dom';
import {ArrowRight,Menu,X,ShoppingBag,MapPin,ExternalLink,Navigation,Plus,Minus} from 'lucide-react';
import {useApp,useContent} from '../App.jsx';
import {safeUrl,mapLinks,widgetEmbed,validateWidget} from '../lib/domain.js';
export const navItems=[['/','Trang chủ','Home'],['/gioi-thieu','Giới thiệu','About'],['/san-pham','Sản phẩm','Products'],['/nha-may','Nhà máy','Facilities'],['/tin-tuc','Tin tức','News'],['/lien-he','Liên hệ','Contact']];
export function Brand(){const content=useContent('site');return <Link to="/" className="brand" aria-label="CEC JSC"><img src={safeUrl(content.heroImage,'image')||'/assets/logo.png'} alt="" width="58" height="58"/><span>{content.title}</span></Link>}
export function Header(){const {lang,setLang,t,state}=useApp();const [open,setOpen]=useState(false);const location=useLocation();const menu=useRef();useEffect(()=>{setOpen(false)},[location.pathname]);useEffect(()=>{const key=e=>{if(e.key==='Escape'){setOpen(false);menu.current?.focus()}};if(open)window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[open]);
 return <><a className="skip-link" href="#main">{t('Bỏ qua menu','Skip to content')}</a><header className="site-header"><div className="container header-inner"><Brand/><nav className={'primary-nav '+(open?'is-open':'')} aria-label={t('Điều hướng chính','Main navigation')} id="primary-menu">{navItems.map(([href,vi,en])=><NavLink key={href} to={href} end={href==='/'}>{t(vi,en)}</NavLink>)}</nav><div className="header-actions"><div className="language" aria-label={t('Ngôn ngữ','Language')}><button aria-pressed={lang==='vi'} onClick={()=>setLang('vi')}>VI</button><span>/</span><button aria-pressed={lang==='en'} onClick={()=>setLang('en')}>EN</button></div><Link className="cart-link" to="/yeu-cau" aria-label={t('Yêu cầu sản phẩm','Product enquiry')}><ShoppingBag size={20}/>{state.cart.length>0&&<span>{state.cart.length}</span>}</Link><button ref={menu} aria-label={t("Menu điều hướng","Navigation menu")} className="menu-toggle" aria-expanded={open} aria-controls="primary-menu" onClick={()=>setOpen(!open)}>{open?<X size={20}/>:<Menu size={20}/>}<span>Menu</span></button></div></div></header></>
}
export function Footer(){const {t}=useApp();const c=useContent('site');return <footer className="site-footer"><div className="container footer-main"><div><Brand/><p>{c.subtitle}</p><p className="footer-description">{c.body}</p></div><div><h3>{t('Khám phá CEC','Explore CEC')}</h3><div className="footer-links">{navItems.slice(1).map(([href,vi,en])=><Link key={href} to={href}>{t(vi,en)}</Link>)}</div></div><div><h3>{t('Kết nối cùng chúng tôi','Connect with us')}</h3><Link className="btn btn-gold" to="/lien-he">{t('Liên hệ','Contact')}<ArrowRight size={17}/></Link></div></div><SocialWidgets placement="footer"/><div className="container footer-bottom"><span>© {new Date().getFullYear()} CEC JSC</span><Link to="/admin">{t('Quản trị','Administration')}</Link></div></footer>}
export function Action({to,children,variant='primary',...props}){return <Link className={'btn btn-'+variant} to={to} {...props}>{children}<ArrowRight size={17}/></Link>}
export function PageHero({page,children,compact=false}){const {t}=useApp();return <section className={'page-hero '+(compact?'compact':'')} style={{backgroundImage:`linear-gradient(90deg,rgba(2,38,62,.9),rgba(2,49,80,.25)),url("${safeUrl(page.heroImage,'image')}")`}}><div className="container"><div className="breadcrumbs"><Link to="/">{t('Trang chủ','Home')}</Link><span>/</span><span>{page.subtitle}</span></div><h1>{page.title}</h1><p>{page.body}</p>{children}</div></section>}
export function SectionTitle({title,description,children}){return <div className="section-heading"><div><h2>{title}</h2>{description&&<p>{description}</p>}</div>{children}</div>}
export function Image({src,alt='',className='',...props}){const [failed,setFailed]=useState(false);useEffect(()=>setFailed(false),[src]);const safe=safeUrl(src,'image');return safe&&!failed?<img src={safe} alt={alt} className={className} loading="lazy" onError={()=>setFailed(true)} {...props}/>:<div className={'image-fallback '+className}><MapPin aria-hidden="true"/><span>{alt||'CEC JSC'}</span></div>}
export function Field({label,id,children,error,textarea=false,...props}){const generated=useId();const fieldId=id||generated;return <div className="field"><label htmlFor={fieldId}>{label}</label>{children?React.cloneElement(children,{id:fieldId,'aria-invalid':Boolean(error),'aria-describedby':error?fieldId+'-error':undefined}):textarea?<textarea id={fieldId} rows={4} {...props} aria-invalid={Boolean(error)} aria-describedby={error?fieldId+'-error':undefined}/>:<input id={fieldId} {...props} aria-invalid={Boolean(error)} aria-describedby={error?fieldId+'-error':undefined}/>} {error&&<p className="field-error" id={fieldId+'-error'}>{error}</p>}</div>}
export function Empty({title,body,children}){return <div className="empty-state"><ShoppingBag size={34}/><h3>{title}</h3><p>{body}</p>{children}</div>}
export function Modal({title,children,onClose,wide=false}){const dialog=useRef();const titleId=useId();useEffect(()=>{const node=dialog.current;const previous=document.activeElement;node.showModal();return()=>{node.close();previous?.focus?.()}},[]);return <dialog ref={dialog} className={wide?'modal wide':'modal'} aria-labelledby={titleId} onCancel={e=>{e.preventDefault();onClose()}} onClick={e=>{if(e.target===dialog.current)onClose()}}><div className="modal-head"><h2 id={titleId}>{title}</h2><button className="icon-button" aria-label="Đóng" onClick={onClose}><X/></button></div><div className="modal-body">{children}</div></dialog>}
export function Confirm({title,body,onConfirm,onClose}){const {t}=useApp();return <Modal title={title} onClose={onClose}><p>{body}</p><div className="form-actions"><button className="btn btn-light" onClick={onClose}>{t('Hủy','Cancel')}</button><button className="btn btn-danger" onClick={onConfirm}>{t('Xóa','Delete')}</button></div></Modal>}
export function MapPanel({facility}){const {t}=useApp();const links=mapLinks(facility);return <section className="map-panel"><div className="map-heading"><div><h3><MapPin size={21}/>{facility.name}</h3><p>{facility.address}</p></div></div><iframe key={links.embed} src={links.embed} title={t('Bản đồ ','Map of ')+facility.name} loading="lazy" allowFullScreen referrerPolicy="strict-origin-when-cross-origin"/><div className="map-actions"><a className="btn btn-primary" href={links.search} target="_blank" rel="noopener noreferrer"><ExternalLink size={17}/>{t('Mở trong Google Maps','Open Google Maps')}</a><a className="btn btn-outline" href={links.directions} target="_blank" rel="noopener noreferrer"><Navigation size={17}/>{t('Chỉ đường','Directions')}</a></div></section>}
export function Quantity({value,onChange,label}){return <div className="quantity"><button type="button" aria-label={'Giảm '+label} onClick={()=>onChange(Math.max(1,Number(value)-1))}><Minus size={16}/></button><input aria-label={label} type="number" min="1" max="1000000" step="1" value={value} onChange={e=>onChange(e.target.value)}/><button type="button" aria-label={'Tăng '+label} onClick={()=>onChange(Math.min(1000000,Number(value)+1))}><Plus size={16}/></button></div>}
export function WidgetView({widget}){const {t}=useApp();if(validateWidget(widget))return null;const embed=widgetEmbed(widget);if(widget.placement==='floating')return <a className={'social-icon social-icon-'+widget.platform} href={safeUrl(widget.url,widget.platform)} target="_blank" rel="noopener noreferrer" aria-label={widget.name+' — '+widget.platform} title={widget.name}><SocialIcon platform={widget.platform}/><span className="social-icon-tooltip">{widget.name}</span></a>;return <div className={'social-widget '+widget.platform}><h3>{widget.name}</h3>{embed&&<iframe src={embed} title={widget.name} loading="lazy" allow="fullscreen" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen/>}<a href={safeUrl(widget.url,widget.platform)} target="_blank" rel="noopener noreferrer"><ExternalLink size={16}/>{t('Xem trên ','Open on ')+widget.platform}</a></div>}
const routePage={'/':'home','/gioi-thieu':'about','/san-pham':'products','/nha-may':'facilities','/tin-tuc':'news','/lien-he':'contact','/yeu-cau':'request'};
export function SocialWidgets({placement='content'}){const {state}=useApp();const location=useLocation();const current=routePage[location.pathname]||routePage['/'+location.pathname.split('/')[1]];const widgets=state.widgets.filter(w=>w.enabled&&w.placement===placement&&(w.page==='all'||w.page===current)).sort((a,b)=>a.order-b.order);return widgets.length?<div className={'widgets widgets-'+placement+(placement==='floating'?'':' container')}>{widgets.map(w=><WidgetView key={w.id} widget={w}/>)}</div>:null;}

