import React,{useRef,useState} from 'react';
import {Bold,Italic,List,Heading2,ImagePlus,Trash2} from 'lucide-react';
import {useApp} from '../App.jsx';
import {Field,Image} from './Common.jsx';
import {safeUrl} from '../lib/domain.js';
export function LocaleTabs({locale,setLocale}){return <div className="locale-tabs" role="group" aria-label="Ngôn ngữ nội dung"><button type="button" className={locale==='vi'?'active':''} aria-pressed={locale==='vi'} onClick={()=>setLocale('vi')}>Tiếng Việt</button><button type="button" className={locale==='en'?'active':''} aria-pressed={locale==='en'} onClick={()=>setLocale('en')}>English</button></div>}
export function ImageEditor({value,onChange,alt='',onAltChange,label='Hình ảnh'}){const {notify}=useApp();const fileRef=useRef();const [error,setError]=useState('');const upload=e=>{const file=e.target.files?.[0];if(!file)return;if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>1500000){setError('Chọn JPG, PNG hoặc WebP tối đa 1,5 MB.');e.target.value='';return}const reader=new FileReader();reader.onerror=()=>setError('Không đọc được ảnh. Hãy chọn lại.');reader.onload=()=>{onChange(reader.result);setError('')};reader.readAsDataURL(file);e.target.value='';};
 return <div className="image-editor"><h3>{label}</h3><Image src={value} alt={alt||label}/><div className="image-controls"><button type="button" className="btn btn-outline" onClick={()=>fileRef.current?.click()}><ImagePlus size={16}/>Chọn ảnh</button><button type="button" className="btn btn-light danger" onClick={()=>onChange('')}><Trash2 size={16}/>Xóa ảnh</button><input ref={fileRef} type="file" accept="image/jpeg,image/png,image/webp" onChange={upload} hidden/></div><Field label="Đường dẫn ảnh HTTPS hoặc /assets/"><input value={value?.startsWith('data:')?'':value||''} placeholder={value?.startsWith('data:')?'Đang dùng ảnh đã tải lên':'https://... hoặc /assets/...'} onChange={e=>{onChange(e.target.value);setError(e.target.value&&!safeUrl(e.target.value,'image')?'Đường dẫn ảnh không hợp lệ.':'')}}/></Field>{onAltChange&&<Field label="Mô tả ảnh (alt text)" value={alt} onChange={e=>onAltChange(e.target.value)}/>}<small>JPG, PNG, WebP · tối đa 1,5 MB. Ảnh được lưu cùng nội dung tại trình duyệt này.</small>{error&&<p className="field-error" role="alert">{error}</p>}</div>
}
export function RichEditor({value,onChange}){const ref=useRef();const insert=(before,after='')=>{const node=ref.current;if(!node)return;const start=node.selectionStart,end=node.selectionEnd;onChange(value.slice(0,start)+before+value.slice(start,end)+after+value.slice(end));requestAnimationFrame(()=>{node.focus();node.setSelectionRange(start+before.length,end+before.length)})};return <div className="rich-editor"><div className="rich-toolbar" role="toolbar" aria-label="Định dạng bài viết"><button type="button" aria-label="In đậm" onClick={()=>insert('**','**')}><Bold size={17}/></button><button type="button" aria-label="In nghiêng" onClick={()=>insert('_','_')}><Italic size={17}/></button><button type="button" aria-label="Tiêu đề" onClick={()=>insert('\n## ')}><Heading2 size={17}/></button><button type="button" aria-label="Danh sách" onClick={()=>insert('\n- ')}><List size={17}/></button></div><textarea ref={ref} aria-label="Nội dung bài viết" rows={10} value={value} onChange={e=>onChange(e.target.value)}/></div>}

