'use strict';
const articleData={
  'uu-dai':{
    title:'Mua xe điện tại Dĩ An: chọn ưu đãi phù hợp, bắt đầu hành trình xanh',category:'Ưu đãi',date:'08.10.2026',read:'6 phút đọc',intro:'Một chiếc xe hợp với bạn, một ngân sách dễ tính toán và một buổi trải nghiệm thật — ba điều giúp việc chuyển sang xe điện trở nên nhẹ nhàng hơn.',
    sections:[['goi-uu-dai','Gói ưu đãi minh họa'],['ngan-sach','Tính ngân sách trước khi chọn'],['nhu-cau','Chọn xe theo nhịp sống'],['trai-nghiem','Trải nghiệm tại showroom'],['cau-hoi','Câu hỏi thường gặp']],
    body:`<div class="article-feature"><div><div class="eyebrow">KHỞI ĐẦU XANH CÙNG HÀ THÀNH</div><strong>Ưu đãi vừa tầm.<br>Hành trình vừa ý.</strong><p>Khám phá xe điện theo cách của bạn.</p></div><img src="assets/evo-premia.webp" alt="Xe máy điện VinFast Evo Grand Premia"></div>
    <p>Buổi sáng đi làm, chiều ghé chợ, cuối tuần hẹn bạn bè: chiếc xe là một phần quen thuộc trong cuộc sống. Khi nghĩ đến việc đổi sang xe điện, nhiều người muốn có một lựa chọn êm ái hơn nhưng vẫn vừa với khoản tiền đã dành dụm. Tại khu vực Dĩ An, nhu cầu đi lại đa dạng khiến việc chọn đúng mẫu xe quan trọng hơn một con số khuyến mãi hấp dẫn.</p>
    <p>Hà Thành Electric giới thiệu cách tìm hiểu xe theo từng bước: xác định nhu cầu, so sánh chi phí và trải nghiệm trực tiếp. Bài viết này được biên soạn cho website demo; các quyền lợi dưới đây là ví dụ để bạn hình dung cách một trang ưu đãi có thể trình bày thông tin.</p>
    <h2 id="goi-uu-dai">01. Một gói ưu đãi dễ hiểu có những gì?</h2>
    <p>Trong bản minh họa, gói khởi đầu xanh gồm giảm 5% trên giá xe demo, quà tặng phụ kiện và buổi tư vấn chi phí trước khi nhận xe. Mỗi quyền lợi được trình bày riêng để người xem dễ biết khoản nào làm giảm tiền mua xe và khoản nào giúp việc sử dụng thuận tiện hơn.</p>
    <ul><li><strong>Giảm giá trực tiếp:</strong> hiển thị giá trước và sau ưu đãi cho đúng mẫu xe đang quan tâm.</li><li><strong>Quà tặng đồng hành:</strong> ví dụ một món phụ kiện hữu ích, được mô tả rõ loại và số lượng.</li><li><strong>Tư vấn chi phí:</strong> cùng người mua xem lại cấu hình pin, bộ sạc và những khoản cần chuẩn bị.</li></ul>
    <div class="article-note"><strong>Ví dụ trong demo:</strong> Một chiếc xe có giá mẫu 20.000.000 đồng sẽ giảm 1.000.000 đồng khi áp dụng mức 5%. Con số này chỉ diễn giải cách tính, không phải báo giá hoặc chính sách đang áp dụng của VinFast.</div>
    <h2 id="ngan-sach">02. Đừng dừng lại ở giá trên thẻ sản phẩm</h2>
    <p>Để đặt ra ngân sách phù hợp, hãy tách chi phí thành ba nhóm: mua xe, chuẩn bị đưa xe vào sử dụng và chi phí trong quá trình đi lại. Cách chia này giúp bạn nhìn thấy rõ khoản phải trả ngay và khoản sẽ phát sinh sau đó.</p>
    <p>Khi trao đổi với showroom, bạn có thể đề nghị một bảng tính cho đúng phiên bản mình chọn. Bảng nên nêu giá xe, cấu hình pin, bộ sạc đi kèm và những mục chưa bao gồm. Nếu có hình thức trả góp, cần xem số tiền trả trước, từng kỳ thanh toán và tổng chi phí của phương án cụ thể.</p>
    <p>Hãy giữ một phần ngân sách cho những vật dụng thực sự cần trong ngày đầu sử dụng. Bạn cũng nên xác định nơi sạc và lịch sạc phù hợp với sinh hoạt gia đình. Có phương án ngay từ đầu sẽ khiến việc đổi xe thuận tiện hơn.</p>
    <h2 id="nhu-cau">03. Chiếc xe phù hợp bắt đầu từ lịch trình của bạn</h2>
    <h3>Với người đi học</h3><p>Hãy chú ý cảm giác khi dắt xe, khả năng chống chân và không gian đặt cặp sách. Người trực tiếp sử dụng nên ngồi thử, quay tay lái và làm quen với các thao tác cơ bản. Thay vì chọn chỉ bằng hình ảnh, một buổi xem xe giúp cả gia đình cùng đánh giá sự phù hợp.</p>
    <h3>Với người đi làm</h3><p>Hãy hình dung một ngày bình thường: quãng đường từ nhà đến công ty, đồ cần mang theo và những điểm thường ghé trên đường về. Tư thế ngồi thoải mái, không gian để đồ và việc sạc thuận tiện có thể ảnh hưởng nhiều đến trải nghiệm lâu dài. Nếu thường chở thêm người, bạn nên thử chỗ ngồi cùng người đi chung.</p>
    <h3>Với người thích dạo phố</h3><p>Màu xe và thiết kế là điểm thu hút đầu tiên, nhưng cảm giác điều khiển cũng cần hợp với bạn. Dành thời gian xem màu thực tế dưới ánh sáng tự nhiên và thử các thao tác khi xe đứng yên. Một chiếc xe khiến bạn thấy tự tin sẽ dễ trở thành người bạn đồng hành mỗi ngày.</p>
    <h2 id="trai-nghiem">04. Chuẩn bị cho một buổi xem xe hiệu quả</h2>
    <p>Trước buổi hẹn, hãy ghi lại hai hoặc ba mẫu xe muốn xem cùng khoảng ngân sách dự kiến. Bạn có thể mang theo chiếc túi thường dùng để thử không gian chứa đồ. Khi trải nghiệm, chú ý tư thế ngồi, tầm nhìn và mức độ dễ sử dụng của các nút điều khiển.</p>
    <ol><li>Trao đổi mục đích sử dụng và những điều bạn muốn cải thiện so với xe hiện tại.</li><li>Xem mẫu xe, phiên bản và màu sắc trực tiếp.</li><li>Nhờ tư vấn viên hướng dẫn thao tác trước khi lái thử trong khu vực phù hợp.</li><li>Đối chiếu cảm nhận thực tế với ngân sách, rồi cân nhắc lựa chọn.</li></ol>
    <h2 id="cau-hoi">05. Những câu hỏi thường gặp</h2>
    <details><summary>Mức giảm 5% trên trang có phải ưu đãi thật không?</summary><p>Đây là nội dung minh họa để xem giao diện website. Khi sử dụng website chính thức, showroom cần cập nhật chương trình, thời hạn và điều kiện cụ thể.</p></details>
    <details><summary>Chưa biết chọn mẫu xe nào thì có thể đăng ký tư vấn không?</summary><p>Bạn có thể chọn “Tôi cần được tư vấn” trong form. Đối với demo, thao tác này chỉ mô phỏng quy trình và không tạo lịch hẹn thật.</p></details>
    <details><summary>Cần xem những gì khi so sánh hai mẫu xe?</summary><p>Hãy so sánh cùng cấu hình, những khoản đi kèm và trải nghiệm khi ngồi thử. Nhu cầu sử dụng thực tế sẽ giúp bạn xác định điểm nào quan trọng nhất.</p></details>`
  },
  'chon-xe':{
    title:'Đi học hay đi làm? Cách chọn chiếc xe điện hợp với bạn',category:'Kinh nghiệm',date:'06.10.2026',read:'4 phút đọc',intro:'Bắt đầu từ những chuyến đi quen thuộc để tìm một chiếc xe vừa thoải mái, vừa phù hợp với cuộc sống hằng ngày.',sections:[['lich-trinh','Hiểu lịch trình của bạn'],['cam-giac','Kiểm tra cảm giác sử dụng'],['so-sanh','So sánh lựa chọn']],
    body:`<div class="article-feature green"><div><div class="eyebrow">YOUR EVERYDAY RIDE</div><strong>Vừa với bạn.<br>Hợp mỗi ngày.</strong><p>Chọn xe từ nhu cầu thực tế.</p></div><img src="assets/evo-lite.webp" alt="VinFast Evo Grand Lite"></div><p>Một chiếc xe đẹp có thể khiến bạn chú ý ngay, nhưng sự phù hợp thường nằm ở những điều nhỏ: dắt xe có nhẹ nhàng không, ngồi có thoải mái không và việc sạc có thuận tiện không. Trước khi xem giá hoặc màu sắc, hãy ghi lại những chuyến đi thường xuyên nhất của mình.</p><h2 id="lich-trinh">01. Hiểu lịch trình trước khi đọc thông số</h2><p>Bạn chủ yếu đi từ nhà đến trường, di chuyển giữa nhiều điểm làm việc hay chỉ cần xe cho những chuyến đi ngắn? Mỗi lịch trình đặt ra những ưu tiên khác nhau. Lập một danh sách các điểm thường đến sẽ giúp cuộc tư vấn tập trung hơn.</p><ul><li>Ghi lại quãng đường đi và về trong một ngày bình thường.</li><li>Liệt kê túi xách, cặp sách hoặc vật dụng thường mang theo.</li><li>Xác định có thường xuyên chở thêm người hay không.</li><li>Kiểm tra nơi đỗ xe và điều kiện sạc.</li></ul><h2 id="cam-giac">02. Những điểm nên thử khi xem xe</h2><p>Hãy ngồi vào vị trí lái và kiểm tra xem bạn có thể chống chân tự tin hay không. Thử đưa tay tới tay lái, nhìn bảng điều khiển và đặt chân theo tư thế tự nhiên. Đừng bỏ qua thao tác dắt xe ra vào chỗ đỗ, vì đây là việc bạn sẽ làm mỗi ngày.</p><p>Với nhu cầu đi học, có thể thử đặt chiếc cặp thường dùng vào cốp. Với nhu cầu đi làm, kiểm tra chỗ để áo mưa và túi đựng vật dụng cá nhân. Nếu thường chở người thân, hãy cùng thử không gian ngồi và tay nắm.</p><div class="article-note"><strong>Mẹo nhỏ:</strong> Viết ra ba điều bạn thích và ba điều còn băn khoăn sau khi xem mỗi mẫu xe. Ghi chú ngay tại buổi trải nghiệm thường hữu ích hơn việc nhớ lại nhiều ngày sau.</div><h2 id="so-sanh">03. So sánh ít lựa chọn, nhưng so sánh thật rõ</h2><p>Thu hẹp còn hai hoặc ba mẫu là một cách giúp quyết định bớt rối. Hãy đặt các lựa chọn cạnh nhau với cùng những tiêu chí: cảm giác ngồi, tiện ích cần dùng, phương án sạc và tổng ngân sách. Điểm số cao nhất nên dành cho yếu tố có ảnh hưởng trực tiếp đến sinh hoạt của bạn.</p><p>Khi vẫn còn phân vân, một buổi trải nghiệm bổ sung có thể giúp bạn rõ hơn về cảm giác điều khiển. Chọn xe là một quyết định sẽ đồng hành lâu dài, vì vậy bạn có thể dành đủ thời gian để cân nhắc.</p>`
  },
  'sac-pin':{
    title:'Lần đầu dùng xe điện: những điều cần biết về pin và sạc',category:'Hướng dẫn',date:'04.10.2026',read:'4 phút đọc',intro:'Làm quen với bộ sạc, nơi sạc và hướng dẫn sử dụng của đúng mẫu xe để xây dựng một thói quen thuận tiện.',sections:[['bo-sac','Bắt đầu từ đúng bộ sạc'],['noi-sac','Chuẩn bị nơi sạc'],['thoi-quen','Xây dựng thói quen']],
    body:`<div class="article-feature"><div><div class="eyebrow">GÓC CHĂM SÓC XE</div><strong>Hiểu pin hơn.<br>Chủ động hơn.</strong><p>Mỗi mẫu xe có hướng dẫn riêng.</p></div><img src="assets/hero-scooter.webp" alt="Xe điện VinFast Kinet"></div><p>Đối với người lần đầu sử dụng xe điện, việc sạc thường là câu hỏi đầu tiên. Một cách bắt đầu dễ dàng là nhờ tư vấn viên hướng dẫn bằng chính bộ sạc và chiếc xe sẽ nhận. Bạn sẽ biết vị trí cổng sạc, cách theo dõi trạng thái và nơi tìm thông tin khi cần.</p><h2 id="bo-sac">01. Làm quen với bộ sạc của chiếc xe</h2><p>Hãy đối chiếu bộ sạc với hướng dẫn và cấu hình của đúng mẫu xe. Kiểm tra các phụ kiện được bàn giao, tìm hiểu ý nghĩa đèn báo và hỏi nơi liên hệ nếu thiết bị hoạt động khác thường. Không áp dụng hướng dẫn của một mẫu xe khác khi chưa xác nhận tính tương thích.</p><p>Trình tự kết nối và ngắt sạc cần theo tài liệu của nhà sản xuất. Nếu chưa chắc chắn, hãy đề nghị tư vấn viên thao tác mẫu trước khi sử dụng lần đầu.</p><h2 id="noi-sac">02. Chuẩn bị một vị trí thuận tiện</h2><p>Nơi sạc nên phù hợp với yêu cầu trong hướng dẫn sử dụng và điều kiện điện tại nhà. Trao đổi trước về khoảng cách từ chỗ đỗ xe đến nguồn điện để biết bạn có thể sử dụng bộ sạc thuận tiện hay không.</p><ul><li>Xem yêu cầu về nguồn điện và vị trí sạc trong tài liệu đi kèm xe.</li><li>Kiểm tra tình trạng bộ sạc và dây kết nối trước khi dùng.</li><li>Giữ khu vực gọn gàng và tránh để người đi lại vướng dây.</li><li>Nhờ đơn vị chuyên môn kiểm tra nguồn điện nếu có điểm chưa rõ.</li></ul><div class="article-note"><strong>Thông tin theo đúng mẫu xe:</strong> Thời gian sạc, cấu hình pin và khả năng tháo pin có thể khác nhau. Các số liệu trên thẻ xe trong website này là minh họa, không dùng thay tài liệu vận hành.</div><h2 id="thoi-quen">03. Tìm lịch sạc hợp với sinh hoạt</h2><p>Sau một thời gian làm quen, bạn sẽ hiểu mức tiêu hao của những hành trình thường đi. Quan sát trạng thái pin trước khi xuất phát và chuẩn bị cho các chuyến đi phát sinh sẽ giúp bạn chủ động hơn trong lịch trình.</p><p>Hãy đọc phần chăm sóc pin của hướng dẫn sử dụng để biết cách xử lý khi ít dùng xe hoặc cần cất giữ lâu. Khi thấy cảnh báo trên xe, lỗi bộ sạc hoặc dấu hiệu bất thường, liên hệ bộ phận dịch vụ để được kiểm tra theo đúng quy trình.</p><p>Buổi tư vấn tại showroom có thể giúp bạn xem lại các thao tác cơ bản và giải đáp những câu hỏi thực tế trong quá trình sử dụng. Một thói quen phù hợp bắt đầu từ việc hiểu rõ thiết bị mình đang dùng.</p>`
  }
};
const key=new URLSearchParams(location.search).get('bai') || 'uu-dai';
const article=articleData[key] || articleData['uu-dai'];
document.title=`${article.title} — Hà Thành Electric`;
document.querySelector('meta[name="description"]').content=article.intro;
document.getElementById('main').innerHTML=`<section class="article-banner"><div class="container"><nav class="breadcrumb" aria-label="Đường dẫn trang"><a href="index.html">Trang chủ</a><span>/</span><a href="index.html#tin-tuc">Góc chuyển động xanh</a><span>/</span><span>${article.category}</span></nav><div class="eyebrow">GÓC CHUYỂN ĐỘNG XANH · ${article.category.toUpperCase()}</div><h1>${article.title}</h1><p class="article-intro">${article.intro}</p><div class="article-meta"><span>Hà Thành Electric</span><span>·</span><span>${article.date}</span><span>·</span><span>${article.read}</span></div></div></section><div class="container article-layout"><article class="article-body">${article.body}<div class="article-end"><h3>Khám phá chiếc xe phù hợp với bạn.</h3><p>Thử form tư vấn hoặc quay lại xem các dòng xe trong demo.</p><button class="button" data-booking>Đăng ký tư vấn & lái thử <span data-icon="arrow"></span></button></div><p class="fine-print">Bài viết mẫu cho website demo, cập nhật tháng 10/2026. Thông tin thương mại, thông số và ưu đãi cần được showroom xác nhận trước khi sử dụng chính thức.</p><div class="related-links"><h3>Bạn có thể quan tâm</h3>${Object.entries(articleData).filter(([,a])=>a!==article).map(([k,a])=>`<a href="article.html?bai=${k}">${a.title} →</a>`).join('')}</div></article><aside class="article-aside" aria-label="Mục lục và tư vấn"><div><div class="toc"><h2>Trong bài viết này</h2>${article.sections.map(([id,label],i)=>`<a href="#${id}">${String(i+1).padStart(2,'0')}. ${label}</a>`).join('')}</div><div class="aside-cta"><div class="eyebrow">BẮT ĐẦU HÀNH TRÌNH XANH</div><h3>Một buổi lái thử,<br>nhiều điều rõ hơn.</h3><p>Ngồi thử, cảm nhận và tìm lựa chọn phù hợp với bạn.</p><button class="button button-white" data-booking>Đăng ký trải nghiệm <span data-icon="arrow"></span></button></div></div></aside></div>`;
